---
algorithm: &algo sync-ppo
name: sync-ppo
info: sync-ppo

precision: 32

n_agents: 1
self_play: False
is_ma_algo: True

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

controller:
  store_period: 5e4
  restart_runners_period: null
  max_pbt_iterations: 1
  max_steps_per_iteration: &ms 5e6
  initialize_rms: &irms True

parameter_server:
  root_dir: *algo
  model_name: *algo

  train_from_scratch_frac: 1
  online_frac: .2

  payoff:
    step_size: 1e-2   # step size towards the most recent data, 0 or null average payoff over the entire history
    update_interval: 180
    sampling_strategy:
      type: pfsp
      p: 1
      threshold: .3

  # rule_strategies:
  #   # agent name / config
  #   random:
  #     aid: 1
  #     vid: 1
  #     path: rule/random   # path to the file that defines Strategy
  #     # other configs

ray_config:
  runner:
    num_cpus: 1
  agent:
    num_gpus: 0

monitor: 
  max_steps: *ms

runner:
  n_runners: 10
  n_steps: &nsteps 100
  push_every_episode: False

env:
  env_name: &env_name grf-academy_pass_and_shoot_with_keeper
  representation: simple115v2
  render: False
  write_full_episode_dumps: False
  write_video: False
  dump_frequency: 1000
  logdir: results/grf
  extra_players: null
  control_left: True
  control_right: False
  shared_policy: True
  score_reward_scale: 1

  max_episode_steps: 200
  use_action_mask: False
  uid2aid: null

  n_envs: &nenvs 10

  use_idx: False
  timeout_done: &td True

agent: {}

monitor:
  use_tensorboard: True

strategy:
  algorithm: *algo
  train_loop: {}

model:
  aid: 0
  gamma: &gamma .99
  use_prev_info: False

  policy:
    nn_id: policy
    units_list: [64, 64]
    w_init: orthogonal
    activation: relu
    norm: layer
    norm_after_activation: True
    out_scale: .01
    rnn_type: &prnn lstm
    rnn_units: 64
    rnn_norm: layer
    use_feature_norm: False
  value:
    nn_id: value
    units_list: [64, 64]
    w_init: orthogonal
    activation: relu
    norm: layer
    norm_after_activation: True
    rnn_type: &vrnn lstm
    rnn_units: 64
    rnn_norm: layer
    use_feature_norm: False

loss:
  # hyperparams for value target and advantage
  target_type: gae
  c_clip: 1
  rho_clip: 1
  adv_type: gae
  norm_adv: True

  prnn_bptt: 10
  vrnn_bptt: 10

  # hyperparams for policy optimization
  pg_type: ppo
  ppo_clip_range: .2
  teammate_ratio_clip: .2
  policy_sample_mask: True

  # hyperparams for value learning
  value_loss: clip_huber
  value_clip_range: .2
  huber_threshold: 10
  value_sample_mask: False
  popart: &popart True

  stats:
    gamma: *gamma
    lam: &lam .95
    pg_coef: 1
    entropy_coef: 5e-3
    value_coef: 1

trainer:
  algorithm: *algo
  aid: 0
  n_runners: &nrunners 2
  n_envs: *nenvs
  n_epochs: &nepochs 1
  n_mbs: &nmbs 1
  n_steps: *nsteps
  update_scheme: whole
  popart: *popart
  debug: False

  theta_opt:
    opt_name: adam
    lr: 5e-4
    clip_norm: 10
    eps: 1e-5

actor:
  update_obs_rms_at_execution: False
  update_obs_at_execution: False
  rms:
    obs:
      obs_names: [obs, global_state]
      obs_normalized_axis: [0, 1]  # obs is normalized at once with the sequential dimension
      obs_normalized_ndim: 2
      normalize_obs: True
      use_feature_mask: True
      obs_clip: 10
    reward:
      reward_normalized_axis: [0, 1] # reward is normalized at once with the sequential dimension
      reward_normalized_ndim: 1
      normalize_reward: False
      update_reward_rms_in_time: False
      gamma: *gamma

buffer:
  type: ac

  n_runners: *nrunners
  n_envs: *nenvs
  n_steps: *nsteps
  queue_size: 2
  timeout_done: *td

  gamma: *gamma
  lam: *lam

  sample_keys: 
    - obs
    - global_state
    - action
    - prev_info
    - value
    - reward
    - discount
    - reset
    - mu_logprob
    - mu_logits
    - state_reset
    - state
