---
algorithm: &algo ppo
name: ppo
info: ppo

precision: 32

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

routine:
  algorithm: *algo

  MAX_STEPS: 5e6
  n_steps: &nsteps 100
  LOG_PERIOD: 1e5
  EVAL_PERIOD: null

  n_eval_envs: 100
  RECORD_VIDEO: False
  N_EVAL_EPISODES: 1
  size: [256, 256]

  model_rollout_type: sim
  compute_return_at_once: False
  ignore_ratio_for_ego: False
  perm: null

env:
  env_name: &env_name mujoco-Walker2d-v3
  n_runners: &nrunners 1
  n_envs: &nenvs 40
  max_episode_steps: 1000
  to_multi_agent: True
  timeout_done: &td False
  # n_bins: 11

agent: {}

monitor:
  use_tensorboard: True

strategy:
  algorithm: *algo
  train_loop: {}

model:
  aid: 0
  joint_log_prob: False
  gamma: &gamma .99

  policy:
    nn_id: policy
    units_list: [64, 64]
    w_init: orthogonal
    activation: tanh
    norm: null
    out_scale: .01
    rnn_type: &prnn null
    rnn_units: 64
    out_act: tanh
    init_std: .2
    sigmoid_scale: True
    std_x_coef: 1.
    std_y_coef: .5
    use_feature_norm: False
  value:
    nn_id: value
    units_list: [64, 64]
    w_init: orthogonal
    activation: tanh
    norm: null
    rnn_type: &vrnn null
    rnn_units: 64
    use_feature_norm: False

loss:
  # hyperparams for value target and advantage
  target_type: gae
  c_clip: 1
  rho_clip: 1
  adv_type: gae
  norm_adv: False
  zero_center: True
  popart: &popart True

  prnn_bptt: 10
  vrnn_bptt: 10

  # hyperparams for policy optimization
  pg_type: ppo
  ppo_clip_range: .2
  policy_sample_mask: True

  # hyperparams for value learning
  value_loss: clip_huber
  huber_threshold: 10
  value_clip_range: .2
  value_sample_mask: False

  stats:
    gamma: *gamma
    lam: &lam .95
    pg_coef: 1
    entropy_coef: .01
    value_coef: 1

trainer:
  algorithm: *algo
  aid: 0
  n_runners: *nrunners
  n_envs: *nenvs
  n_epochs: &nepochs 10
  n_mbs: &nmbs 5
  n_steps: *nsteps

  popart: *popart

  policy_opt:
    opt_name: Adam
    lr: 3e-4
    clip_norm: 10
    eps: 1e-5
  value_opt:
    opt_name: Adam
    lr: 3e-4
    clip_norm: 10
    eps: 1e-5

actor:
  update_obs_rms_at_execution: False
  update_obs_at_execution: False
  rms:
    obs:
      obs_names: [obs]
      obs_normalized_axis: [0, 1]
      obs_normalized_ndim: 2
      normalize_obs: True
      obs_clip: 10
    reward:
      reward_normalized_axis: [0, 1] # reward is normalized at once with the sequential dimension
      reward_normalized_ndim: 1
      normalize_reward: False
      update_reward_rms_in_time: False
      gamma: *gamma

buffer:
  type: ac

  n_runners: *nrunners
  n_envs: *nenvs
  n_steps: *nsteps
  queue_size: 2
  timeout_done: *td

  gamma: *gamma
  lam: *lam

  sample_keys: 
    - obs
    - action
    - value
    - reward
    - discount
    - reset
    - mu_logprob
    - mu_loc
    - mu_scale
    - state_reset
    - state
    - advantage
    - v_target
